version: "3.8"
services:
  python-server:
    build: .
    restart: always
    command: python /code/source/server.py
    networks:
      dockerize-sample-network:
        aliases:
          - python-app
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    links:
      - python-server
    depends_on:
      - python-server
    networks:
      - dockerize-sample-network

networks:
  dockerize-sample-network:
